add android

diff --git a/.github/workflows/build-box2d.yml b/.github/workflows/build-box2d.yml
--- a/.github/workflows/build-box2d.yml
+++ b/.github/workflows/build-box2d.yml
@@ -218,4 +218,56 @@ jobs:
         path: external/box2d/build/Box2D/box2d-3.1.0-${{ matrix.platform }}.tar.gz
         if-no-files-found: error
         retention-days: 1
+      
+  build-android:
+    strategy:
+      matrix:
+        platform: [arm64-android]
+    runs-on: ubuntu-22.04
+    steps:
+    - name: Checkout repo
+      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+
+    - name: Setup NDK
+      uses: nttld/setup-ndk@v1
+      id: setup-ndk
+      with:
+        ndk-version: r25b
+        add-to-path: false
+
+    - name: Install
+      run: |
+        sudo apt-get install -y --no-install-recommends libc6-dev-i386
+        sudo apt-get install -y --no-install-recommends gcc-multilib
+
+    - name: Install dependencies
+      run: ci/ci.sh install --platform=${{ matrix.platform }}
+
+    - name: Build Box2D
+      env:
+        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
+        ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
+      run: |
+        ./scripts/build.py --save-env-path=ci/env.sh save_env
+        source ci/env.sh
+        echo "DYNAMO_HOME=$DYNAMO_HOME"
+        #export PATH="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
+        ./scripts/build.py install_waf
+        cd external/box2d
+        PREFIX=$DYNAMO_HOME waf configure --platform=${{ matrix.platform }}
+        waf install
         
+
+    - name: Check artifact existence
+      run: |
+        if [ ! -f external/box2d/build/Box2D/box2d-3.1.0-${{ matrix.platform }}.tar.gz ]; then
+          echo "Artifact not found. Listing contents of external/box2d/build/Box2D:"
+          ls -lh external/box2d/build/Box2D || echo "Directory missing"
+        fi
+    - name: Archive results (platform-specific)
+      uses: actions/upload-artifact@v4
+      with:
+        name: box2d-3.1.0-${{ matrix.platform }}.tar.gz
+        path: external/box2d/build/Box2D/box2d-3.1.0-${{ matrix.platform }}.tar.gz
+        if-no-files-found: error
+        retention-days: 1
