improve ci

diff --git a/.github/workflows/build-glfw.yml b/.github/workflows/build-glfw.yml
--- a/.github/workflows/build-glfw.yml
+++ b/.github/workflows/build-glfw.yml
@@ -31,11 +31,19 @@ jobs:
       run: |
         cd share/ext
         ./build.sh glfw ${{ matrix.platform }}
+    - name: Check artifact existence and list folder
+      run: |
+        if [ ! -f share/ext/glfw/glfw-3.4-${{ matrix.platform }}.tar.gz ]; then
+          echo "Artifact not found. Listing contents of share/ext/glfw:"
+          ls -lh share/ext/glfw || echo "Directory missing"
+        fi
     - name: Archive results
       uses: actions/upload-artifact@v4
       with:
         name: glfw-3.4-${{ matrix.platform }}.tar.gz
         path: share/ext/glfw/glfw-3.4-${{ matrix.platform }}.tar.gz
+        if-no-files-found: error
+        retention-days: 1
 
   build-linux-arm:
     strategy:
@@ -60,11 +68,19 @@ jobs:
       run: |
         cd share/ext
         ./build.sh glfw ${{ matrix.platform }}
+    - name: Check artifact existence and list folder
+      run: |
+        if [ ! -f share/ext/glfw/glfw-3.4-${{ matrix.platform }}.tar.gz ]; then
+          echo "Artifact not found. Listing contents of share/ext/glfw:"
+          ls -lh share/ext/glfw || echo "Directory missing"
+        fi
     - name: Archive results
       uses: actions/upload-artifact@v4
       with:
         name: glfw-3.4-${{ matrix.platform }}.tar.gz
         path: share/ext/glfw/glfw-3.4-${{ matrix.platform }}.tar.gz
+        if-no-files-found: error
+        retention-days: 1
 
   build-macos:
     strategy:
@@ -88,11 +104,19 @@ jobs:
       run: |
         cd share/ext
         ./build.sh glfw ${{ matrix.platform }}
+    - name: Check artifact existence and list folder
+      run: |
+        if [ ! -f share/ext/glfw/glfw-3.4-${{ matrix.platform }}.tar.gz ]; then
+          echo "Artifact not found. Listing contents of share/ext/glfw:"
+          ls -lh share/ext/glfw || echo "Directory missing"
+        fi
     - name: Archive results
       uses: actions/upload-artifact@v4
       with:
         name: glfw-3.4-${{ matrix.platform }}.tar.gz
         path: share/ext/glfw/glfw-3.4-${{ matrix.platform }}.tar.gz
+        if-no-files-found: error
+        retention-days: 1
 
   build-windows:
     strategy:
@@ -116,8 +140,16 @@ jobs:
       run: |
         cd share/ext
         ./build.sh glfw ${{ matrix.platform }}
+    - name: Check artifact existence and list folder
+      run: |
+        if [ ! -f share/ext/glfw/glfw-3.4-${{ matrix.platform }}.tar.gz ]; then
+          echo "Artifact not found. Listing contents of share/ext/glfw:"
+          ls -lh share/ext/glfw || echo "Directory missing"
+        fi
     - name: Archive results
       uses: actions/upload-artifact@v4
       with:
         name: glfw-3.4-${{ matrix.platform }}.tar.gz
         path: share/ext/glfw/glfw-3.4-${{ matrix.platform }}.tar.gz
+        if-no-files-found: error
+        retention-days: 1
