add web builds

diff --git a/.github/workflows/build-box2d.yml b/.github/workflows/build-box2d.yml
--- a/.github/workflows/build-box2d.yml
+++ b/.github/workflows/build-box2d.yml
@@ -273,3 +273,59 @@ jobs:
         path: external/box2d/build/Box2D/box2d-3.1.0-${{ matrix.platform }}.tar.gz
         if-no-files-found: error
         retention-days: 1
+
+  build-web:
+    strategy:
+      matrix:
+        platform: [js-web, wasm-web, wasm_pthread-web]
+    runs-on: ubuntu-22.04
+    steps:
+    - name: Checkout repo
+      uses: actions/checkout@v4
+      with:
+        ref: '${{ env.BUILD_BRANCH }}'
+
+    - name: Setup emsdk
+      uses: mymindstorm/setup-emsdk@v14
+      with:
+        version: '4.0.6'
+
+    - name: Install Python
+      uses: actions/setup-python@v5
+      with:
+        python-version: 3.13
+
+    - name: Install dependencies
+      run: ci/ci.sh install --platform=${{ matrix.platform }}
+
+    - name: Build Box2D
+      env:
+        EMCC_FORCE_STDLIBS: 1
+      run: |
+        ./scripts/build.py --save-env-path=ci/env.sh save_env
+        source ci/env.sh
+        echo "DYNAMO_HOME=$DYNAMO_HOME"
+        source "$EMSDK/emsdk_env.sh"
+        export CC=emcc
+        export CXX=em++
+        export CFLAGS="-DBOX2D_DISABLE_SIMD"
+        export CXXFLAGS="$CFLAGS"
+        ./scripts/build.py install_waf
+        cd external/box2d
+        CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" CC="$CC" CXX="$CXX" PREFIX=$DYNAMO_HOME waf configure --platform=${{ matrix.platform }}
+        waf install
+
+    - name: Check artifact existence
+      run: |
+        if [ ! -f external/box2d/build/Box2D/box2d-3.1.0-${{ matrix.platform }}.tar.gz ]; then
+          echo "Artifact not found. Listing contents of external/box2d/build/Box2D:"
+          ls -lh external/box2d/build/Box2D || echo "Directory missing"
+        fi
+
+    - name: Archive results (platform-specific)
+      uses: actions/upload-artifact@v4
+      with:
+        name: box2d-3.1.0-${{ matrix.platform }}.tar.gz
+        path: external/box2d/build/Box2D/box2d-3.1.0-${{ matrix.platform }}.tar.gz
+        if-no-files-found: error
+        retention-days: 1
