please python on windows. work!

diff --git a/.github/workflows/build-box2d.yml b/.github/workflows/build-box2d.yml
--- a/.github/workflows/build-box2d.yml
+++ b/.github/workflows/build-box2d.yml
@@ -156,7 +156,11 @@ jobs:
       run: |
         python ./scripts/build.py --save-env-path=ci/env.sh save_env
         source ci/env.sh
+        echo "Restoring PATH from ORIGINAL_PATH"
+        export PATH="$ORIGINAL_PATH"
         echo "DYNAMO_HOME=$DYNAMO_HOME"
+        which python || echo "python not found"
+        python --version || echo "cannot run python"
         python ./scripts/build.py install_waf
         cd external/box2d
         PREFIX=$DYNAMO_HOME waf configure --platform=${{ matrix.platform }}
